Repository luckyframework/avram, pull requests merged in 2020-10, with the labels that each got.

#469 New Interface for Operations
  spec/define_attribute_spec.cr
  spec/operation_callbacks_spec.cr
  spec/operation_needs_spec.cr
  spec/operation_spec.cr
  src/avram/callbacks.cr
  src/avram/errors.cr
  src/avram/needy_initializer.cr
  src/avram/operation.cr
  src/avram/save_operation.cr
Labels: BREAKING CHANGE, clarify api

#481 Better callbacks for SaveOperation
  spec/save_operation_callbacks_spec.cr
  spec/validations_spec.cr
  src/avram/callbacks.cr
  src/avram/save_operation.cr
Labels: BREAKING CHANGE

#492 Clarify which method is preferred + fix update example
  src/avram/needy_initializer_and_save_methods.cr
Labels: improve error experience
